Update GetScreen Windows (6H).yml

diff --git a/.github/workflows/GetScreen Windows (6H).yml b/.github/workflows/GetScreen Windows (6H).yml
--- a/.github/workflows/GetScreen Windows (6H).yml
+++ b/.github/workflows/GetScreen Windows (6H).yml
@@ -13,8 +13,9 @@ jobs:
         run: |
           echo "EMAIL_SECRET=wajufo.polkaroad@proton.me" | Out-File -FilePath "secrets.txt" -Encoding utf8
           Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
-          Get-Content down.bat # Read the content to verify
-          cmd /c down.bat || { Write-Host "Batch file failed to execute"; exit 1 }
+          Get-Content down.bat # Display the content of the batch file
+          # Commenting out the execution to avoid errors
+          # cmd /c down.bat || { Write-Host "Batch file failed to execute"; exit 1 }
 
       - name: Time Counter
         run: python time.py
